
### GET todos los usuarios
GET http://localhost:3000/users

### POST Crear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "id": 1,
  "firstname": "rthtrh",
  "lastname": "Ihrthrtbeas",
  "email": "oshrthrtcar@gmail.com",
  "birthDate": "1987-11-20",
  "address": {
    "id": 1,
    "street": "Avenrfnrnrnida 2",
    "city": "Gertrttafe",
    "country": "UK",
    "postalcode": "28905"
  }
}

### GET un usuario por id
GET http://localhost:3000/users/1

### PUT Modificar un usuario
PUT http://localhost:3000/users/4
Content-Type: application/json

{
  "id": 4,
  "firstname": "JAvier",
  "lastname": "Gonzalez",
  "email": "JAG@gmail.com",
  "birthDate": "1991-10-12",
  "address": {
    "id": 4,
    "street": "Plaza de España 5",
    "city": "Burgos",
    "country": "ES",
    "postalcode": "09001"
  }
}

### DELETE Borrar un usuario
DELETE http://localhost:3000/users/4